### ISSUE TITLE
i18n の導入

### ISSUE THREAD

**Issue by KOHEI183** [quadraticvotingJP/quadratic-voting-jp#11]
# ゴール
# 概要
# タスク
- [ ]

**Comment by Pianoopera** [comment]
参考文献

- [The easiest way to translate your NextJs apps\. \| BestofReactjs](https://bestofreactjs.com/repo/isaachinman-next-i18next-react-nextjs-extensions)
- [Next\.js で国際化\(i18n\)対応サイトを作る \- Goodpatch Tech Blog](https://goodpatch-tech.hatenablog.com/entry/2021/07/20/190715)
- [Advanced Features: Internationalized Routing \| Next\.js](https://nextjs.org/docs/advanced-features/i18n-routing)
