### ISSUE TITLE
クレジットのレスポンシブ

### ISSUE THREAD

**Issue by KOHEI183** [quadraticvotingJP/quadratic-voting-jp#161]
# ゴール
# 概要
<img width="804" alt="スクリーンショット 2022-04-30 21 08 55" src="https://user-images.githubusercontent.com/55649762/166104960-b6e76fbf-ebc6-40c7-8d68-68b99f4e1c2c.png">

# タスク
- [ ]

**Comment by Pianoopera** [comment]
こちらで対応
[投票コンポーネント修正](https://github.com/quadraticvotingJP/quadratic-voting-jp/pull/243)
