### ISSUE TITLE
vercelの調査

### ISSUE THREAD

**Issue by KOHEI183** [quadraticvotingJP/quadratic-voting-jp#171]
# ゴール
画面遷移の調査
# 概要
dashboardへ遷移ができないため調査をする
buildがおかしいかも
# タスク
- [ ]

**Comment by quadraticvotingJP** [comment]
## 備忘録
主に二ヶ所エラーが発生

* toLocaleString()メソッドがundefindeになってしまう問題
* 多言語対応で取り入れたi18nがSSR時に動作していなかった
