### ISSUE TITLE
git flowを忠実に再現したいためbranchの自動削除の制御する

### ISSUE THREAD

**Issue by KOHEI183** [quadraticvotingJP/quadratic-voting-jp#291]
# 現状
現在ブランチの運用にgit-flowを採用しているが、github上のブランチを自動削除設定するとhotfixやreleaseブランチまで自動で削除されてしまう

# ゴール
自動削除機能を設定しつつ、特定の接頭語が入ったブランチは保護するように設定を行う

# 概要
https://efcl.info/2020/04/18/delete-github-branches/
# タスク
- [ ]

**Comment by quadraticvotingJP** [comment]
##  備忘録
githubのブランチ保護は対応できなさそう

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches#require-deployments-to-succeed-before-merging
