### ISSUE TITLE
googleAdSenseの疎通

### ISSUE THREAD

**Issue by KOHEI183** [quadraticvotingJP/quadratic-voting-jp#292]
# ゴール
# 概要
# タスク
- [ ]

**Comment by Pianoopera** [comment]
## 備忘録
`net::ERR_BLOCKED_BY_CLIENT`に関するエラー
### エラー理由
エラーになる理由としては広告ブロックを行うSidekickで動作確認をしていたため
クロームで確認する必要があった。
### Todo
Chromeで確認を行い下記エラーを対応予定
```
T {message: 'adsbygoogle.push() error: No slot size for availableWidth=194', name: 'TagError', pbr: 
```
