### ISSUE TITLE
投票画面：投票後に再度リンクを開くとエラーとなる

### ISSUE THREAD

**Issue by Pianoopera** [quadraticvotingJP/quadratic-voting-jp#353]
# ゴール
投票後の画面制御でpropsを渡すか、制御をssr内で実施する方向に戻す

# 概要
投票後にpropsで渡す値が足りないためエラーが起きていそう
必要な値を送るよう修正対応を行う

# タスク
- [ ]

**Comment by KOHEI183** [comment]
解決したためclose
